---
  - name: Ensure Samba is installed.
    ansible.builtin.apt:
      name:
        - samba

  - name: Ensure Samba user exists.
    ansible.builtin.user:
      name: "{{ item.username }}"
      shell: /sbin/nologin
      create_home: no
    loop:
        "{{ users }}"

  - name: Ensure backups parent location exists.
    ansible.builtin.file:
      path: "{{ backups_path }}"
      state: directory
      mode: u=rwx,g=rx,o=rx

  - name: Ensure backups location exists.
    ansible.builtin.file:
      path: "{{ backups_path }}/{{ item.username }}"
      state: directory
      owner: "{{ item.username }}"
    loop:
        "{{ users }}"

  - name: Ensure Samba configuration directory exists.
    ansible.builtin.file:
      path: /etc/samba/smb.conf.d
      state: directory

  - name: Ensure Time Machine Samba config exists.
    ansible.builtin.template:
      src: templates/timemachine.j2
      dest: "/etc/samba/smb.conf.d/timemachine-{{ item.username }}.conf"
    loop:
        "{{ users }}"

  - name: Ensure Time Machine Samba config is sourced.
    ansible.builtin.lineinfile:
      path: /etc/samba/smb.conf
      line: "include = /etc/samba/smb.conf.d/timemachine-{{ item.username }}.conf"
    loop:
        "{{ users }}"

  - name: Set Samba user's password.
    shell: '
      (echo {{ item.password }}; echo {{ item.password }}) |
      smbpasswd -s -a {{ item.username }}
    '
    loop:
        "{{ users }}"

  - name: Forcibly reload the Samba service.
    ansible.builtin.service:
      name: smbd
      state: reloaded
      enabled: true
